services:
  nginx:
    profiles: ["preprod"]
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: afyia-website
    ports:
      - "8000:80"
    volumes:
      - ./dist/afyia-website/browser:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  angular-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: docker/angular/Dockerfile
    container_name: afyia-website-dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - "4200:4200"
    environment:
    - SSR_API_URL=http://api:3001
    - SSR_IMAGE_URL=http://api:3001/uploads

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: afyia-api
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
      - ./directus/database/afyiadb.sqlite:/app/afyiadb.sqlite
      - /etc/ssl/letsencrypt/certs:/etc/ssl/letsencrypt/certs
    env_file:
      - ./api/.env
    environment:
      - NODE_ENV=development

  directus:
    profiles: ["dev", "preprod"]
    image: directus/directus:11.5.1
    container_name: afyia-directus
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./api/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      SECRET: "secret"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/afyiadb.sqlite"
      WEBSOCKETS_ENABLED: "true"
