server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        return 302 /en/;
    }

    location /fr/ {
        alias /usr/share/nginx/html/fr/;
        try_files $uri $uri/ /fr/index.html;
    }

    location /en/ {
        alias /usr/share/nginx/html/en/;
        try_files $uri $uri/ /en/index.html;
    }

    location / {
        try_files $uri $uri/ /en/index.html;
    }
}
